### ISSUE TITLE
Flutter error in announcements page

### ISSUE THREAD

**Issue by gicorada** [scevor/scevor-app#2]
**Describe the bug**
Adding an announcement while in the page results in a dart error:
```
The following _TypeError was thrown building:
type 'String' is not a subtype of type 'int'

When the exception was thrown, this was the stack: 
#0      _AnnouncementsState.build.<anonymous closure>.<anonymous closure> (package:scevor/pages/Announcements.dart:39:63)
#1      SliverChildBuilderDelegate.build (package:flutter/src/widgets/scroll_delegate.dart:489:22)
#2      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:828:28)
#3      SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:758:67)
#4      Iterable.forEach (dart:core/iterable.dart:346:35)
#5      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:805:24)
#6      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:734:7)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
[78 more...]

``` 

**To Reproduce**
1. Go to 'Annunci'
2. Add an announcement from Supabase while in the page

**Expected behavior**
The announcement displays at the top of the page

**Smartphone:**
 - OS: Android
 - Version: 9, 10

**Additional context**
The next time the page is opened, announcements load normally

**Comment by gicorada** [comment]
It seems that Supabase sends the realtime data in a different order than normal, so the parameter which is treated as an id is instead the content of the announcement. When a complete new request is made, the order of the parameters is correct.
I've assigned this issue to myself, because I'm already trying to resolve this issue
